---
deployment:
  tasks:
    - export DEPLOYPATH=/home/danigrou/api.danigroup.co.za
    - /bin/cp -r backend/. $DEPLOYPATH
    - cd frontend && npm install && npm run build && cd ..
    - /bin/cp -r frontend/dist/. /home/danigrou/dms.danigroup.co.za